scheduler_interval: 20

message_types:
  - name: agent_update
    description: Notification that a new agent was added or an existing agent was modified
    template: templates/messages/agent_update.md

agents:
  - name: operator
    type: source
    consumes: []
    produces: []

  - name: pipeline_builder
    type: source
    consumes: []
    produces:
      - type: agent_update
        to: []
        description: Notification that a new agent was added or modified
